### ISSUE TITLE
Criando TDD de empréstimos de livros

### ISSUE THREAD

**Issue by PedroDiSanti** [PedroDiSanti/library-api#11]
## TODO

* [x] Criar teste de empréstimo de livros
* [x] Criar DTO de empréstimo de livros
* [x] Criar Controller de empréstimo de livros
* [x] Criar Service de empréstimo de livros
* [X] Abstrair exceptions referentes a APIs
* [X] Implementar teste referentes à livros.
