### ISSUE TITLE
Criando TDD de services e repository de empréstimos de livros e suas camadas implementadas

### ISSUE THREAD

**Issue by PedroDiSanti** [PedroDiSanti/library-api#13]
## TODO

* [x] Criar teste de empréstimo de livros
* [x] Criar DTO de empréstimo de livros
* [x] Criar Service de empréstimo de livros
* [x] Criar Repository de empréstimo de livros
* [X] Abstrair exceptions referentes a APIs
