### ISSUE TITLE
Implementar TDD da classe de serviço de livros

### ISSUE THREAD

**Issue by PedroDiSanti** [PedroDiSanti/library-api#3]
## TODO

* [X] Adicionar dependência ModelMapper
* [X] Criar teste da camada de serviço
* [X] Criando a implementação da camada de serviço
* [X] Implementar Bean Validation e Exception Handler
* [X] Implementar erros de regra de negócio
* [X] Testar fluxo de exceção na camada de serviço
