### ISSUE TITLE
Criar teste de integração, busca, deleção e atualização de livro e suas exceções.

### ISSUE THREAD

**Issue by PedroDiSanti** [PedroDiSanti/library-api#5]
## TODO

* [x] Criar teste de integração com a base de dados
* [x] Criar TDD do método de leitura de um livro
* [x] Criar TDD do método de atualização de um livro
* [x] Criar TDD do método de deleção de um livro
* [x] Criar exceções dos métodos desenvolvidos
