### ISSUE TITLE
Criar testes e serviços de atualização e deleção de livros

### ISSUE THREAD

**Issue by PedroDiSanti** [PedroDiSanti/library-api#7]
## TODO

* [x] Criar teste na camada de serviço de atualização de livros
* [x] Criar teste na camada de serviço de deleção de livros
* [X] Criar serviçoes de atualização e deleção de livros
