### ISSUE TITLE
Criando testes de integração para métodos save e delete do repository e criando tdd de filtro de livros com Example.

### ISSUE THREAD

**Issue by PedroDiSanti** [PedroDiSanti/library-api#9]
## TODO

* [x] Criar teste no repository para o método save
* [x] Criar teste no repository para o método delete
* [X] Criar design TDD para API de consulta de livros por parâmetros
* [X] Criar teste e service para API de consulta de livros por parâmetros
* [X] Criar teste e controller para API de consulta de livros por parâmetros
* [X] Implementar API de consulta de livros por parâmetros
